---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone_test

steps:
  - name: startSlack
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: bot
      icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
      username: drone
      template: >
        *start* building *{{repo.name}}*:*{{build.branch}}* #{{build.number}}.
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      branch:
        - dev
        - stag
        - master
      event:
        - push

  - name: sendStagingWebhookKeel
    pull: if-not-exists
    image: curlimages/curl:7.75.0
    commands:
      - curl -H "Content-Type: application/json" http://keel-stag.mnews.tw/v1/webhooks/native
#      - curl -H 'Content-Type: application/json' --request POST --data "{}" http://keel-stag.mnews.tw/v1/webhooks/native
#      - curl -H "Content-Type: application/json" --request POST --data "{\"name\":\"gcr.io/mirror-tv-275709/mirror-tv-nuxt\",\"tag\":\"stag__188\"}" http://keel-stag.mnews.tw/v1/webhooks/native
#      - curl -H "Content-Type: application/json" --request POST --data "{\"name\":\"gcr.io/mirror-tv-275709/${DRONE_REPO_NAME}\",\"tag\":\"${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}\"}" http://keel-stag.mnews.tw/v1/webhooks/native
    when:
      branch:
        - stag
        - master
      event:
        - push

  - name: finishSlack
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: bot
      icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
      username: drone
      template: >
        {{#success build.status}}
          *success* ${DRONE_REPO_NAME}:${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER} was well served.
          Check out the new <https://github.com|drone_test>.
        {{else}}
          Houston, we have a problem. Build #{{build.number}} failed.
        {{/success}}
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      branch:
        - dev
        - stag
        - master
      event:
        - push
      status:
        - success
        - failure
